<?php
$section_params = array(
	'row_type' => "image"
,'type_width' =>'full_size'
,'row_fit_to_height'=>'enable'
,'box_size_states'=>'content_box_size'
,'el_class'=>''
,'row_vertical_align'=>'enable'
,'row_equal_column_heigh'=>'yes'
,'row_content_vertical_align'=>'middle'
,'row_padding_top'=>'250'
,'row_padding_bottom'=>'250'
,'row_padding_right'=>'0'
,'row_padding_left'=>'0'
,'row_margin_top'=>'0'
,'row_margin_bottom'=>'0'
,'background_color'=>'rgba(255,255,255,1)'
,'row_webm_url'=>''
,'row_mp4_url'=>''
,'background_color_image'=>'rgba(0, 0, 0, 0.2)'
,'row_image_position'=>'default'
,'row_bg_image_size_tab_image'=>'cover'
,'row_bg_repeat_image_gp='=>'no'
,'first_color'=>'#000'
,'second_color'=>'#000'
,'row_gradient_color'=>'pixflow_base64eyJjb2xvcjEiOiIjZmZmIiwiY29sb3IyIjoicmdiYSgyNTUsMjU1LDI1NSwwKSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0='
,'row_image_position_gradient'=>'fit'
,'row_bg_image_size_tab_gradient'=>'cover'
,'row_bg_repeat_gradient_gp'=>'no'
,'row_inner_shadow'=>'no'
,'row_sloped_edge'=>'no'
,'row_slope_edge_position'=>'top'
,'row_sloped_edge_color'=>'#000'
,'row_sloped_edge_angle'=>'-3'
,'parallax_status'=>'yes'
,'parallax_speed'=>'1'
,'row_image' => 'http://theme.pixflow.net/massive-dynamic/section/section-44/16.jpg'



, 'content' => '[vc_column el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgba(0,0,0,0)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="36"  padding_bottom="0" padding_left="0" border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);border-style:solid;background-color:rgba(0,0,0,0);background-size:;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:36px!important;padding-bottom:0px;padding-left:0px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}"  md_laptop_visibility="enable" md_tablet_portrait_visibility="enable" md_tablet_landscape_visibility="enable" md_tablet_portrait_width="12" md_mobile_portrait_visibility="enable" md_mobile_landscape_visibility="enable" el_id=\'5a8951423a188\'][md_live_text meditor_letter_spacing="0"       meditor_line_height="1.5"         md_live_text_animation="yes" md_live_text_animation_type="fade" md_live_text_animation_speed="800" md_live_text_animation_delay="0.3" md_live_text_animation_position="left" md_live_text_animation_show="once" md_live_text_animation_easing="Power4.easeOut" md_live_text_parallax_speed="1"]CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9ImxpbmUtaGVpZ2h0OiAxLjVlbTsiIGNsYXNzPSIiPjxzcGFuIHN0eWxlPSJsaW5lLWhlaWdodDogMS41ZW07IiBjbGFzcz0ia2VlcC10ZXh0LXNlbGVjdGVkIj48c3BhbiBzdHlsZT0ibGluZS1oZWlnaHQ6IDEuNWVtOyIgY2xhc3M9IiI+PGI+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZTogNDhweDsgbGluZS1oZWlnaHQ6IDEuNWVtOyBjb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyIgY2xhc3M9IiI+V2XigJlyZSBhIEdyb3VwIG9mCkRlc2lnbmVycyBXaXRoIEFuIEFmZmluaXR5IApGb3IgRGlnaXRhbCBFeHBlcmllbmNlcy48L3NwYW4+PC9iPjwvc3Bhbj48L3NwYW4+PC9zcGFuPjwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIA==[/md_live_text][vc_empty_space height="33"][/vc_empty_space][md_button button_style="fill-rectangle" button_size="standard" left_right_padding="0" button_align="left" button_text="Explore Agency" button_icon_class="icon-empty" button_color="rgb(255, 255, 255)" button_text_color="rgb(49, 49, 49)" button_bg_hover_color="#9b9b9b" button_hover_color="#FFF" button_url="#" button_target="_self" ninja_popup_validate="no" ninja_popup_form_id="undefined" md_button_animation="yes" md_button_animation_type="fade" md_button_animation_speed="800" md_button_animation_delay="0.4" md_button_animation_position="left" md_button_animation_show="once" md_button_animation_easing="Power4.easeOut" md_button_parallax_speed="1" align="left"][/md_button][vc_empty_space height="38"][/vc_empty_space][/vc_column][vc_column el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgba(0,0,0,0)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="0" padding_bottom="0" padding_left="0" border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);border-style:solid;background-color:rgba(0,0,0,0);background-size:;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}" md_laptop_visibility="enable" md_tablet_portrait_visibility="enable" md_tablet_landscape_visibility="enable" md_tablet_portrait_width="12" md_mobile_portrait_visibility="enable" md_mobile_landscape_visibility="enable" el_id=\'5a8951423a216\'][md_video md_video_host="youtube" md_video_url_mp4="" md_video_url_webm="" md_video_url_ogg="" md_video_url_youtube="https://www.youtube.com/watch?v=tcxlSrYEkq8" md_video_url_vimeo="" md_video_style="squareImage" md_video_solid_color="rgba(20,20,20,1)" md_video_image="http://theme.pixflow.net/massive-dynamic/section/section-44/17.jpg" md_video_size="100" md_video_animation="yes" md_video_animation_type="fade" md_video_animation_speed="800" md_video_animation_delay="0.3" md_video_animation_position="center" md_video_animation_show="once" md_video_animation_easing="Power4.easeOut" md_video_parallax_speed="1" align="right"][/md_video][/vc_column]'
);
