<?php
$section_params = array(
	'row_type' => "none"
,'type_width' =>'full_size'
,'row_fit_to_height'=>'enable'
,'box_size_states'=>'content_full_size'
,'el_class'=>''
,'row_vertical_align'=>'enable'
,'row_equal_column_heigh'=>'enable'
,'row_content_vertical_align'=>'0'
,'row_padding_top'=>'100'
,'row_padding_bottom'=>'100'
,'row_padding_right'=>'0'
,'row_padding_left'=>'0'
,'row_margin_top'=>'0'
,'row_margin_bottom'=>'0'
,'background_color'=>'rgba(255,255,255,1)'
,'row_webm_url'=>''
,'row_mp4_url'=>''
,'background_color_image'=>'rgba(0, 0, 0, 0.2)'
,'row_image_position'=>'default'
,'row_bg_image_size_tab_image'=>'cover'
,'row_bg_repeat_image_gp='=>'no'
,'first_color'=>'#000'
,'second_color'=>'#000'
,'row_gradient_color'=>'pixflow_base64eyJjb2xvcjEiOiIjZmZmIiwiY29sb3IyIjoicmdiYSgyNTUsMjU1LDI1NSwwKSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0='
,'row_image_position_gradient'=>'fit'
,'row_bg_image_size_tab_gradient'=>'cover'
,'row_bg_repeat_gradient_gp'=>'no'
,'row_inner_shadow'=>'no'
,'row_sloped_edge'=>'no'
,'row_slope_edge_position'=>'top'
,'row_sloped_edge_color'=>'#000'
,'row_sloped_edge_angle'=>'-3'
,'parallax_status'=>'enable'
,'parallax_speed'=>'0'


, 'content' => '[vc_column][md_live_text is_new_shortcode="yes"  meditor_line_height="1.5"  meditor_letter_spacing="0"]PGRpdiBzdHlsZT0idGV4dC1hbGlnbjogY2VudGVyOyI+PHNwYW4gc3R5bGU9ImxldHRlci1zcGFjaW5nOiAwcHg7IiBjbGFzcz0iIj48c3BhbiBzdHlsZT0iZm9udC1zaXplOiA3MHB4Ij48Yj5EZXZpY2UgRnJpZW5kbHk8L2I+PC9zcGFuPjwvc3Bhbj48L2Rpdj4=[/md_live_text][md_live_text is_new_shortcode="yes"  meditor_line_height="1.5"  meditor_letter_spacing="0"]PGRpdiBzdHlsZT0idGV4dC1hbGlnbjogY2VudGVyOyI+PHNwYW4gc3R5bGU9ImxldHRlci1zcGFjaW5nOiAwcHg7Ij48YnI+PC9zcGFuPjwvZGl2PjxkaXYgc3R5bGU9InRleHQtYWxpZ246IGNlbnRlcjsiPjxzcGFuIHN0eWxlPSJsZXR0ZXItc3BhY2luZzogMHB4OyI+SXQgaXMgYSBsb25nIGVzdGFibGlzaGVkIGZhY3QgdGhhdCBhIHJlYWRlciB3aWxsIGJlIGRpc3RyYWN0ZWQgYnkgdGhlIHJlYWRhYmxlPC9zcGFuPjwvZGl2PjxkaXYgc3R5bGU9InRleHQtYWxpZ246IGNlbnRlcjsiPjxzcGFuIHN0eWxlPSJsZXR0ZXItc3BhY2luZzogMHB4OyI+Y29udGVudCBvZiBhIHBhZ2Ugd2hlbiBsb29raW5nIGF0IGl0cyBsYXlvdXQuPC9zcGFuPjwvZGl2Pg==[/md_live_text][vc_empty_space height="80"][/vc_empty_space][md_slider_carousel slider_images="http://theme.pixflow.net/massive-dynamic/section/section-40/11.jpg,http://theme.pixflow.net/massive-dynamic/section/section-40/12.jpg,http://theme.pixflow.net/massive-dynamic/section/section-40/13.jpg" slider_heights="600" slider_margin="20" slider_nav_active_color="rgb(36, 36, 36)" slider_shadow="yes" slider_auto_play="yes" slider_slider_speed="5" md_slider_carousel_animation_type="fade" md_slider_carousel_animation_speed="200" md_slider_carousel_animation_delay="0" md_slider_carousel_animation_position="center" md_slider_carousel_animation_show="once" md_slider_carousel_animation_easing="Quart.easeInOut"][/md_slider_carousel][/vc_column]'
);
