<?php
$section_params = array(
'box_size_states'=>'content_full_size'
,'row_padding_top'=>'0'
,'row_section_id_description' => ''
,'row_padding_bottom'=>'0'
,'row_type_width_description'=>''
,'row_padding_right'=>'0'
,'row_padding_left'=>'0'
,'row_margin_top'=>'0'
,'row_margin_bottom'=>'0'


, 'content' => '[vc_column width="6/12" el_id=\'58f1ae9fede88\'][md_imagebox_full imagebox_title="Designed &amp; Developed" imagebox_heading_size="h5" imagebox_description="Massive Dynamic is created by a team of 12 experienced professional developers and designers. The team has focused on user experience and ease of use in every aspect of this project." imagebox_general_color="rgb(255, 255, 255)" imagebox_text_height="450" imagebox_alignment="left" imagebox_use_background="yes" imagebox_background="http://theme.pixflow.net/massive-dynamic/section/section-31/section31-2.jpg" imagebox_overlay="yes" imagebox_overlay_color="rgba(0, 0, 0, 0.23)" imagebox_button="yes" imagebox_button_style="slide" imagebox_button_text="Read more" imagebox_button_icon="icon-chevron-right" imagebox_button_color="#fff" imagebox_button_text_color="#fff" imagebox_button_bg_hover_color="#9b9b9b" imagebox_button_hover_color="rgb(3, 155, 70)" imagebox_button_size="standard" imagebox_left_right_padding="0" imagebox_button_url="http://demo.massivedynamic.co/corporate/portfolios/helen-blace/" imagebox_button_target="_self" md_imagebox_full_animation="no" md_imagebox_full_animation_type="fade" md_imagebox_full_animation_speed="200" md_imagebox_full_animation_delay="0.0" md_imagebox_full_animation_position="center" md_imagebox_full_animation_show="once" md_imagebox_full_animation_easing="Quart.easeInOut" md_imagebox_full_parallax_speed="1"][/md_imagebox_full][/vc_column][vc_column width="6/12" el_id=\'58f1ae9fedecd\'][md_imagebox_full imagebox_title="Create Unique Demos" imagebox_heading_size="h5" imagebox_description="Massive Dynamic is created by a team of 12 experienced professional developers and designers. The team has focused on user experience and ease of use in every aspect of this project." imagebox_general_color="rgb(255, 255, 255)" imagebox_text_height="450" imagebox_alignment="left" imagebox_use_background="yes" imagebox_background="http://theme.pixflow.net/massive-dynamic/section/section-31/section31-3.jpg" imagebox_overlay="yes" imagebox_overlay_color="rgba(0, 0, 0, 0.23)" imagebox_button="yes" imagebox_button_style="slide" imagebox_button_text="Read more" imagebox_button_icon="icon-chevron-right" imagebox_button_color="#fff" imagebox_button_text_color="#fff" imagebox_button_bg_hover_color="#9b9b9b" imagebox_button_hover_color="rgb(3, 155, 70)" imagebox_button_size="standard" imagebox_left_right_padding="0" imagebox_button_url="http://demo.massivedynamic.co/corporate/portfolios/lucas-johnson/" imagebox_button_target="_self" md_imagebox_full_animation="no" md_imagebox_full_animation_type="fade" md_imagebox_full_animation_speed="200" md_imagebox_full_animation_delay="0.0" md_imagebox_full_animation_position="center" md_imagebox_full_animation_show="once" md_imagebox_full_animation_easing="Quart.easeInOut" md_imagebox_full_parallax_speed="1"][/md_imagebox_full][/vc_column]'
);

