<?php
$section_params = array(
	'row_type' => "none"
,'type_width' =>'full_size'
,'row_fit_to_height'=>'enable'
,'box_size_states'=>'content_full_size'
,'el_class'=>''
,'row_vertical_align'=>'enable'
,'row_equal_column_heigh'=>'enable'
,'row_content_vertical_align'=>'0'
,'row_padding_top'=>'0'
,'row_padding_bottom'=>'0'
,'row_padding_right'=>'0'
,'row_padding_left'=>'0'
,'row_margin_top'=>'0'
,'row_margin_bottom'=>'0'
,'background_color'=>'rgba(255,255,255,1)'
,'row_webm_url'=>''
,'row_mp4_url'=>''
,'background_color_image'=>'rgba(0, 0, 0, 0.2)'
,'row_image_position'=>'default'
,'row_bg_image_size_tab_image'=>'cover'
,'row_bg_repeat_image_gp='=>'no'
,'first_color'=>'#000'
,'second_color'=>'#000'
,'row_gradient_color'=>'pixflow_base64eyJjb2xvcjEiOiIjZmZmIiwiY29sb3IyIjoicmdiYSgyNTUsMjU1LDI1NSwwKSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0='
,'row_image_position_gradient'=>'fit'
,'row_bg_image_size_tab_gradient'=>'cover'
,'row_bg_repeat_gradient_gp'=>'no'
,'row_inner_shadow'=>'no'
,'row_sloped_edge'=>'no'
,'row_slope_edge_position'=>'top'
,'row_sloped_edge_color'=>'#000'
,'row_sloped_edge_angle'=>'-3'
,'parallax_status'=>'enable'
,'parallax_speed'=>'0'

, 'content' => '[vc_column el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgba(0,0,0,0)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="0" padding_bottom="0" padding_left="0" border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);border-style:solid;background-color:rgba(0,0,0,0);background-size:;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}" md_laptop_visibility="enable" md_tablet_portrait_visibility="enable" md_tablet_landscape_visibility="enable" md_tablet_portrait_width="12" md_mobile_portrait_visibility="enable" md_mobile_landscape_visibility="enable"][md_imagebox_full imagebox_title="Eco Camp Patagonia Wildlife Safari" imagebox_heading_size="h3" imagebox_description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porta, mi ut facilisis ullamcorper, magna risus vehicula augue, eget faucibus magna massa at justo. Sed quis augue ut eros tincidunt hendrerit eu eget nisl. Duis malesuada vehicula massa...
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porta, mi ut facilisis ullamcorper, magna risus vehicula augue." imagebox_general_color="#ffffff" imagebox_text_height="750" imagebox_alignment="center" imagebox_use_background="yes" imagebox_background="http://theme.pixflow.net/massive-dynamic/section/section-37/7.jpg" imagebox_overlay="yes" imagebox_overlay_color="rgba(0, 0, 0, 0.13)" imagebox_button="yes" imagebox_button_style="fill-oval" imagebox_button_text="Read More" imagebox_button_icon="icon-empty" imagebox_button_color="#fff" imagebox_button_text_color="rgb(46, 46, 46)" imagebox_button_bg_hover_color="rgb(210, 210, 210)" imagebox_button_hover_color="rgb(255, 255, 255)" imagebox_button_size="standard" imagebox_left_right_padding="10" imagebox_button_url="#" imagebox_button_target="_blank" md_imagebox_full_animation_type="fade" md_imagebox_full_animation_speed="200" md_imagebox_full_animation_delay="0.0" md_imagebox_full_animation_position="center" md_imagebox_full_animation_show="once" md_imagebox_full_animation_easing="Quart.easeInOut" md_imagebox_full_parallax_speed="1"][/md_imagebox_full][/vc_column][vc_column el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgba(0,0,0,0)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="0" padding_bottom="0" padding_left="0" border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);border-style:solid;background-color:rgba(0,0,0,0);background-size:;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}" md_laptop_visibility="enable" md_tablet_portrait_visibility="enable" md_tablet_landscape_visibility="enable" md_tablet_portrait_width="12" md_mobile_portrait_visibility="enable" md_mobile_landscape_visibility="enable"][md_imagebox_full imagebox_title="Liverpool Metrololitan Cathedral" imagebox_heading_size="h3" imagebox_description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porta, mi ut facilisis ullamcorper, magna risus vehicula augue, eget faucibus magna massa at justo. Sed quis augue ut eros tincidunt hendrerit eu eget nisl. Duis malesuada vehicula massa...
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porta, mi ut facilisis ullamcorper, magna risus vehicula augue." imagebox_general_color="#ffffff" imagebox_text_height="750" imagebox_alignment="center" imagebox_use_background="yes" imagebox_background="http://theme.pixflow.net/massive-dynamic/section/section-37/8.jpg" imagebox_overlay="yes" imagebox_overlay_color="rgba(0, 0, 0, 0.13)" imagebox_button="yes" imagebox_button_style="fill-oval" imagebox_button_text="Read More" imagebox_button_icon="icon-empty" imagebox_button_color="#fff" imagebox_button_text_color="rgb(46, 46, 46)" imagebox_button_bg_hover_color="rgb(210, 210, 210)" imagebox_button_hover_color="rgb(255, 255, 255)" imagebox_button_size="standard" imagebox_left_right_padding="10" imagebox_button_url="#" imagebox_button_target="_blank" md_imagebox_full_animation_type="fade" md_imagebox_full_animation_speed="200" md_imagebox_full_animation_delay="0.0" md_imagebox_full_animation_position="center" md_imagebox_full_animation_show="once" md_imagebox_full_animation_easing="Quart.easeInOut" md_imagebox_full_parallax_speed="1"][/md_imagebox_full][/vc_column]'
);
