<?php
$section_params = array(
  'row_type' => "image"
,'type_width' =>'full_size'
,'row_fit_to_height'=>'enable'
,'box_size_states'=>'content_box_size'
,'el_class'=>''
,'row_vertical_align'=>'enable'
,'row_equal_column_heigh'=>'enable'
,'row_content_vertical_align'=>'0'
,'row_padding_top'=>'240'
,'row_padding_bottom'=>'375'
,'row_padding_right'=>'0'
,'row_padding_left'=>'0'
,'row_margin_top'=>'0'
,'row_margin_bottom'=>'0'
,'background_color'=>'rgba(255,255,255,1)'
,'row_webm_url'=>''
,'row_mp4_url'=>''
,'background_color_image'=>'rgba(0, 0, 0, 0.1)'
,'row_image_position'=>'default'
,'row_bg_image_size_tab_image'=>'cover'
,'row_bg_repeat_image_gp='=>'no'
,'first_color'=>'#000'
,'second_color'=>'#000'
,'row_gradient_color'=>'pixflow_base64eyJjb2xvcjEiOiIjZmZmIiwiY29sb3IyIjoicmdiYSgyNTUsMjU1LDI1NSwwKSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0='
,'row_image_position_gradient'=>'fit'
,'row_bg_image_size_tab_gradient'=>'cover'
,'row_bg_repeat_gradient_gp'=>'no'
,'row_inner_shadow'=>'no'
,'row_sloped_edge'=>'no'
,'row_slope_edge_position'=>'top'
,'row_sloped_edge_color'=>'#000'
,'row_sloped_edge_angle'=>'-3'
,'parallax_status'=>'enable'
,'parallax_speed'=>'0'
,'row_image' => 'http://theme.pixflow.net/massive-dynamic/section/section-34/34.jpg'

, 'content' => '[vc_column el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgba(0,0,0,0)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="0" padding_bottom="0" padding_left="0" border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);border-style:solid;background-color:rgba(0,0,0,0);background-size:;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}" md_laptop_visibility="enable" md_tablet_portrait_visibility="enable" md_tablet_landscape_visibility="enable" md_tablet_portrait_width="12" md_mobile_portrait_visibility="enable" md_mobile_landscape_visibility="enable"][md_live_text meditor_letter_spacing="0"    meditor_line_height="1"    md_live_text_animation_speed="800" md_live_text_animation_position="left" md_live_text_animation_show="scroll" md_live_text_animation_easing="Power4.easeOut" md_live_text_animation="yes" md_live_text_animation_delay="0.3" align="left"]CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9IiIgY2xhc3M9IiI+PHNwYW4gc3R5bGU9ImNvbG9yOiByZ2IoMTI0LCAxMjQsIDEyNCk7Ij5JbiBhIHVzZXItY2VudHJpYyB3b3JsZAogd2UgZG88L3NwYW4+PC9zcGFuPiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA=[/md_live_text][vc_empty_space height="20"][/vc_empty_space][md_live_text meditor_letter_spacing="0"    meditor_line_height="1"    md_live_text_animation_speed="800" md_live_text_animation_position="left" md_live_text_animation_show="scroll" md_live_text_animation_easing="Power4.easeOut" md_live_text_animation="yes" md_live_text_animation_delay="0.4"]CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9ImxpbmUtaGVpZ2h0OiAxLjJlbTsiIGNsYXNzPSJrZWVwLXRleHQtc2VsZWN0ZWQiPjxzcGFuIHN0eWxlPSJsaW5lLWhlaWdodDogMS4yZW07IGZvbnQtZmFtaWx5OiAmcXVvdDtPcGVuIFNhbnMmcXVvdDs7IiBjbGFzcz0iIj48c3BhbiBzdHlsZT0iZm9udC1zaXplOiA0OHB4OyBsaW5lLWhlaWdodDogMS4yZW07IGNvbG9yOiByZ2IoMzUsIDMxLCAzMik7Ij48c3BhbiBkYXRhLWZvbnQtd2VpZ2h0PSI2MDAiIHN0eWxlPSJmb250LXN0eWxlOiBub3JtYWw7IGxpbmUtaGVpZ2h0OiAxLjJlbTsiPjxzcGFuIHN0eWxlPSJsaW5lLWhlaWdodDogMS4yZW07IiBjbGFzcz0iIj48c3BhbiBkYXRhLWZvbnQtd2VpZ2h0PSI0MDAiIHN0eWxlPSJmb250LXN0eWxlOiBub3JtYWw7IGZvbnQtZmFtaWx5OiAmcXVvdDtPcGVuIFNhbnMmcXVvdDs7Ij48Yj5TaG93Y2FzZSBhbnl0aGluZyB3aXRoIGEgYmVhdXRpZnVsICZhbXA7IG1vZGVybiBwYXJhbGxheCBwcmVzZW50YXRpb24uPC9iPjwvc3Bhbj48L3NwYW4+PC9zcGFuPjwvc3Bhbj48L3NwYW4+PC9zcGFuPiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA=[/md_live_text][vc_empty_space height="30"][/vc_empty_space][md_button button_style="fill-rectangle" button_text="Explore Agency" button_icon_class="icon-empty" button_color="rgb(0, 108, 241)" button_bg_hover_color="rgb(47, 140, 254)" md_button_animation_speed="800" md_button_animation_position="left" md_button_animation_show="scroll" md_button_animation_easing="Power4.easeOut" ninja_popup_form_id="undefined" md_button_animation="yes" md_button_animation_delay="0.5" align="left"][/md_button][/vc_column][vc_column width="6/12"][/vc_column]'
);
