<?php
$section_params = array(
	'row_type' => "image",
	'type_width' => "full_size" ,
	'box_size_states' => "content_box_size",
	'el_class' => "responsive-laptop" ,
	'row_fit_to_height' => "no" ,
	'row_vertical_align' => "no" ,
	'row_equal_column_heigh' => "no" ,
	'row_content_vertical_align' => "0" ,
	'row_padding_top' => "280",
	'row_padding_bottom' => "280",
	'row_padding_right' => "0",
	'row_padding_left' => "0",
	'row_margin_top' => "0",
	'row_margin_bottom' => "0" ,
	'background_color' => "rgba(255,255,255,1)" ,
	'row_webm_url' => "" ,
	'row_mp4_url' => "" ,
	'background_color_image' => "rgba(0, 0, 0, 0.38)" ,
	'row_image' => "http://theme.pixflow.net/massive-dynamic/section/section-12/communication.jpg"  ,
	'row_image_position' => "default",
	'row_bg_image_size_tab_image' => "cover",
	'row_bg_repeat_image_gp' => "no" ,
	'first_color' => "#000" ,
	'second_color' => "#000" ,
	'row_gradient_color' => "pixflow_base64eyJjb2xvcjEiOiIjZmZmIiwiY29sb3IyIjoicmdiYSgyNTUsMjU1LDI1NSwwKSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0=" ,
	'row_image_position_gradient' => "fit" ,
	'row_bg_image_size_tab_gradient' => "cover" ,
	'row_bg_repeat_gradient_gp' => "no" ,
	'row_inner_shadow' => "no" ,
	'row_sloped_edge' => "no" ,
	'row_slope_edge_position' => "top" ,
	'row_sloped_edge_color' => "#000" ,
	'row_sloped_edge_angle' => "-3" ,
	'parallax_status' => "yes" ,
	'parallax_speed' => "5" ,
	'content' => '[vc_column width="6/12" el_class="responsive-full-width"][md_live_text meditor_letter_spacing="0"  meditor_line_height="1"  md_live_text_animation="yes" md_live_text_animation_type="fade" md_live_text_animation_speed="800" md_live_text_animation_delay="0.3" md_live_text_animation_position="bottom" md_live_text_animation_show="once" md_live_text_animation_easing="Power4.easeOut" md_live_text_parallax_speed="1" align="left"]CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgPGgzIHN0eWxlPSJsaW5lLWhlaWdodDogMWVtOyI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBMYXRvOyBsaW5lLWhlaWdodDogMWVtOyIgY2xhc3M9IiI+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZTogNjZweDsgbGluZS1oZWlnaHQ6IDFlbTsgY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgZm9udC1mYW1pbHk6IExhdG87IGZvbnQtc3R5bGU6IG5vcm1hbDsiIGNsYXNzPSIiPjxiIHN0eWxlPSIiPkdyb3cgWW91cjwvYj48L3NwYW4+PC9zcGFuPjwvaDM+PGgzIHN0eWxlPSJsaW5lLWhlaWdodDogMWVtOyI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBMYXRvOyBsaW5lLWhlaWdodDogMWVtOyIgY2xhc3M9IiI+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZTogNjZweDsgbGluZS1oZWlnaHQ6IDFlbTsgY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgZm9udC1mYW1pbHk6IExhdG87IGZvbnQtc3R5bGU6IG5vcm1hbDsiIGNsYXNzPSIiPjxiIHN0eWxlPSIiPkNvbW11bml0eSBUb2RheTwvYj48L3NwYW4+PC9zcGFuPjwvaDM+ICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICA=[/md_live_text][md_live_text meditor_letter_spacing="0"  meditor_line_height="1"  md_live_text_animation="yes" md_live_text_animation_type="fade" md_live_text_animation_speed="800" md_live_text_animation_delay="0.4" md_live_text_animation_position="bottom" md_live_text_animation_show="once" md_live_text_animation_easing="Power4.easeOut" md_live_text_parallax_speed="1" align="left"]CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICA8ZGl2PjxzcGFuIHN0eWxlPSJjb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyBmb250LWZhbWlseTogTGF0bzsgZm9udC1zaXplOiAyMHB4OyBsZXR0ZXItc3BhY2luZzogMHB4OyI+PGJyPjwvc3Bhbj48L2Rpdj48ZGl2PjxzcGFuIHN0eWxlPSJjb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyBmb250LWZhbWlseTogTGF0bzsgZm9udC1zaXplOiAyMHB4OyBsZXR0ZXItc3BhY2luZzogMHB4OyI+V2UgdGFrZSBwcmlkZSBpbiBkZWxpdmVyaW5nIEludGVsbGlnZW50IGRlc2lnbnMgYW5kIGVuZ2FnaW5nJm5ic3A7PC9zcGFuPjxicj48L2Rpdj48ZGl2PjxkaXY+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZTogMjBweDsgbGluZS1oZWlnaHQ6IDEuN2VtOyBjb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyBmb250LXdlaWdodDogMzAwOyBmb250LWZhbWlseTogTGF0bzsgZm9udC1zdHlsZTogbm9ybWFsOyIgY2xhc3M9ImtlZXAtdGV4dC1zZWxlY3RlZCIgZGF0YS1mb250LXdlaWdodD0iMzAwIj48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAyMHB4OyBsaW5lLWhlaWdodDogMS43ZW07IGNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7IGZvbnQtZmFtaWx5OiBMYXRvOyBmb250LXdlaWdodDogMzAwOyBmb250LXN0eWxlOiBub3JtYWw7IiBjbGFzcz0iIiBkYXRhLWZvbnQtd2VpZ2h0PSIzMDAiPmV4cGVyaWVuY2VzIGZvciBjbGllbnRzIGFsbCBvdmVyIHRoZSB3b3JsZC48L3NwYW4+PC9zcGFuPjwvZGl2PjxkaXY+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZTogMjBweDsgbGluZS1oZWlnaHQ6IDEuN2VtOyBjb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyBmb250LXdlaWdodDogMzAwOyBmb250LWZhbWlseTogTGF0bzsgZm9udC1zdHlsZTogbm9ybWFsOyIgY2xhc3M9ImtlZXAtdGV4dC1zZWxlY3RlZCIgZGF0YS1mb250LXdlaWdodD0iMzAwIj48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAyMHB4OyBsaW5lLWhlaWdodDogMS43ZW07IGNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7IGZvbnQtZmFtaWx5OiBMYXRvOyBmb250LXdlaWdodDogMzAwOyBmb250LXN0eWxlOiBub3JtYWw7IiBjbGFzcz0iIiBkYXRhLWZvbnQtd2VpZ2h0PSIzMDAiPjxicj48L3NwYW4+PC9zcGFuPjwvZGl2PiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAg[/md_live_text][md_button button_style="fill-rectangle" button_size="standard" left_right_padding="15" button_align="left" button_text="Community" button_icon_class="icon-empty" button_color="#ba001a" button_text_color="rgb(255, 255, 255)" button_bg_hover_color="rgb(226, 20, 39)" button_hover_color="rgb(255, 255, 255)" button_url="#" button_target="_self" ninja_popup_validate="no" ninja_popup_form_id="undefined" md_button_animation="yes" md_button_animation_type="fade" md_button_animation_speed="800" md_button_animation_delay="0.5" md_button_animation_position="bottom" md_button_animation_show="scroll" md_button_animation_easing="Power4.easeOut" md_button_parallax_speed="1" align="left"][/md_button][/vc_column][vc_column width="6/12"][/vc_column]'
);

