<?php
$section_params = array(
	'row_type' => "image"
,'type_width' =>'full_size'
,'row_fit_to_height'=>'enable'
,'box_size_states'=>'content_box_size'
,'el_class'=>''
,'row_vertical_align'=>'enable'
,'row_equal_column_heigh'=>'enable'
,'row_content_vertical_align'=>'0'
,'row_padding_top'=>'300'
,'row_padding_bottom'=>'300'
,'row_padding_right'=>'0'
,'row_padding_left'=>'0'
,'row_margin_top'=>'0'
,'row_margin_bottom'=>'0'
,'background_color'=>'rgba(255,255,255,1)'
,'row_webm_url'=>''
,'row_mp4_url'=>''
,'background_color_image'=>'rgba(0, 0, 0, 0.2)'
,'row_image_position'=>'default'
,'row_bg_image_size_tab_image'=>'cover'
,'row_bg_repeat_image_gp='=>'no'
,'first_color'=>'#000'
,'second_color'=>'#000'
,'row_gradient_color'=>'pixflow_base64eyJjb2xvcjEiOiIjZmZmIiwiY29sb3IyIjoicmdiYSgyNTUsMjU1LDI1NSwwKSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0='
,'row_image_position_gradient'=>'fit'
,'row_bg_image_size_tab_gradient'=>'cover'
,'row_bg_repeat_gradient_gp'=>'no'
,'row_inner_shadow'=>'no'
,'row_sloped_edge'=>'no'
,'row_slope_edge_position'=>'top'
,'row_sloped_edge_color'=>'#000'
,'row_sloped_edge_angle'=>'-3'
,'parallax_status'=>'enable'
,'parallax_speed'=>'0'
,'row_image' => 'http://theme.pixflow.net/massive-dynamic/section/section-51/28.jpg'



, 'content' => '[vc_column][md_live_text meditor_letter_spacing="0"  meditor_line_height="1"  md_live_text_animation="yes" md_live_text_animation_type="fade" md_live_text_animation_speed="800" md_live_text_animation_delay="0.3" md_live_text_animation_position="bottom" md_live_text_animation_show="once" md_live_text_animation_easing="Power4.easeOut" md_live_text_parallax_speed="1"]CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgPGRpdiBzdHlsZT0idGV4dC1hbGlnbjogY2VudGVyOyI+PGIgc3R5bGU9ImxldHRlci1zcGFjaW5nOiAwcHg7Ij48c3BhbiBzdHlsZT0iY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgZm9udC1zaXplOiA0OHB4OyBsaW5lLWhlaWdodDogMS43ZW07IiBjbGFzcz0iIj5TdWJzY3JpYmU8L3NwYW4+PC9iPjwvZGl2PiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAg[/md_live_text][md_live_text meditor_letter_spacing="0"  meditor_line_height="2"  md_live_text_animation="yes" md_live_text_animation_type="fade" md_live_text_animation_speed="800" md_live_text_animation_delay="0.4" md_live_text_animation_position="bottom" md_live_text_animation_show="once" md_live_text_animation_easing="Power4.easeOut" md_live_text_parallax_speed="1"]CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgPGRpdiBzdHlsZT0idGV4dC1hbGlnbjogY2VudGVyOyI+PHNwYW4gc3R5bGU9ImxldHRlci1zcGFjaW5nOiAwcHg7IGxpbmUtaGVpZ2h0OiAyZW07IiBjbGFzcz0ia2VlcC10ZXh0LXNlbGVjdGVkIj48c3BhbiBzdHlsZT0iY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgZm9udC1zaXplOiAyNHB4OyBsaW5lLWhlaWdodDogMmVtOyIgY2xhc3M9IiI+U3Vic2NyaWJlIHRvIGdldCBtb250aGx5IHByb2R1Y3RzIHVwZGF0ZXMgYW5kIGV4Y2x1c2l2ZSBvZmZlcnM8L3NwYW4+PC9zcGFuPjwvZGl2PiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAg[/md_live_text][md_subscribe_business button_icon_class="icon-empty" general_color="rgb(255, 255, 255)" button_text_color="rgb(40, 40, 40)" md_subscribe_business_animation="yes" md_subscribe_business_animation_type="fade" md_subscribe_business_animation_speed="800" md_subscribe_business_animation_delay="0.5" md_subscribe_business_animation_position="bottom" md_subscribe_business_animation_show="once" md_subscribe_business_animation_easing="Power4.easeOut" md_subscribe_business_parallax_speed="1"][/md_subscribe_business][/vc_column]'
);
