<?php
$section_params = array(
	'row_type' => "none"
,'type_width' =>'full_size'
,'row_fit_to_height'=>'enable'
,'box_size_states'=>'content_box_size'
,'el_class'=>''
,'row_vertical_align'=>'enable'
,'row_equal_column_heigh'=>'yes'
,'row_content_vertical_align'=>'middle'
,'row_padding_top'=>'100'
,'row_padding_bottom'=>'100'
,'row_padding_right'=>'0'
,'row_padding_left'=>'0'
,'row_margin_top'=>'0'
,'row_margin_bottom'=>'0'
,'background_color'=>'rgba(255,255,255,1)'
,'row_webm_url'=>''
,'row_mp4_url'=>''
,'background_color_image'=>'rgba(0, 0, 0, 0.2)'
,'row_image_position'=>'default'
,'row_bg_image_size_tab_image'=>'cover'
,'row_bg_repeat_image_gp='=>'no'
,'first_color'=>'#000'
,'second_color'=>'#000'
,'row_gradient_color'=>'pixflow_base64eyJjb2xvcjEiOiIjZmZmIiwiY29sb3IyIjoicmdiYSgyNTUsMjU1LDI1NSwwKSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0='
,'row_image_position_gradient'=>'fit'
,'row_bg_image_size_tab_gradient'=>'cover'
,'row_bg_repeat_gradient_gp'=>'no'
,'row_inner_shadow'=>'no'
,'row_sloped_edge'=>'no'
,'row_slope_edge_position'=>'top'
,'row_sloped_edge_color'=>'#000'
,'row_sloped_edge_angle'=>'-3'
,'parallax_status'=>'enable'
,'parallax_speed'=>'0'

, 'content' => '[vc_column el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgba(0,0,0,0)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="0" padding_bottom="0" padding_left="0" border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);border-style:solid;background-color:rgba(0,0,0,0);background-size:;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}" md_laptop_visibility="enable" md_tablet_portrait_visibility="enable" md_tablet_landscape_visibility="enable" md_tablet_portrait_width="12" md_mobile_portrait_visibility="enable" md_mobile_landscape_visibility="enable"][md_image_box_slider image_box_slider_image="http://theme.pixflow.net/massive-dynamic/section/section-38/9.jpg" image_box_slider_height="800" image_box_slider_size="cover" image_box_slider_hover_link="" image_box_slider_hover_link_target="_self" image_box_slider_effect_slider="fade" image_box_slider_speed="3000" image_box_slider_hover="no" image_box_slider_hover_effect="text" image_box_slider_hover_text="Text Hover" image_box_slider_hover_text_effect="light" md_image_box_slider_animation="yes" md_image_box_slider_animation_type="fade" md_image_box_slider_animation_speed="800" md_image_box_slider_animation_delay="0.3" md_image_box_slider_animation_position="left" md_image_box_slider_animation_show="once" md_image_box_slider_animation_easing="Power4.easeOut" md_image_box_slider_parallax_speed="1"][/md_image_box_slider][/vc_column][vc_column el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgba(0,0,0,0)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="136" padding_bottom="0" padding_left="0" border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);border-style:solid;background-color:rgba(0,0,0,0);background-size:;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:136px;padding-bottom:0px;padding-left:0px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}" md_laptop_visibility="enable" md_tablet_portrait_visibility="enable" md_tablet_landscape_visibility="enable" md_tablet_portrait_width="12" md_mobile_portrait_visibility="enable" md_mobile_landscape_visibility="enable"][md_live_text meditor_letter_spacing="0"   meditor_line_height="1"   md_live_text_animation="yes" md_live_text_animation_type="fade" md_live_text_animation_speed="800" md_live_text_animation_delay="0.3" md_live_text_animation_position="right" md_live_text_animation_show="once" md_live_text_animation_easing="Power4.easeOut" md_live_text_parallax_speed="1"]CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9ImxpbmUtaGVpZ2h0OiAxLjJlbTsiIGNsYXNzPSIiPjxiIHN0eWxlPSIiIGNsYXNzPSIiPjxzcGFuIHN0eWxlPSJmb250LXNpemU6IDQwcHg7IGxpbmUtaGVpZ2h0OiAxLjJlbTsiPk9wdGltaXplZCBmdW5jdGlvbmFsaXR5IAphbnl3aGVyZSB5b3Ugd2lzaDwvc3Bhbj48L2I+PC9zcGFuPiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAg[/md_live_text][vc_empty_space height="25"][/vc_empty_space][md_live_text meditor_letter_spacing="0"   meditor_line_height="1"   md_live_text_animation="yes" md_live_text_animation_type="fade" md_live_text_animation_speed="800" md_live_text_animation_delay="0.4" md_live_text_animation_position="right" md_live_text_animation_show="once" md_live_text_animation_easing="Power4.easeOut" md_live_text_parallax_speed="1"]CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9ImxpbmUtaGVpZ2h0OiAxLjVlbTsgZm9udC1zaXplOiAxOHB4OyIgY2xhc3M9IiI+PHNwYW4gc3R5bGU9ImNvbG9yOiByZ2IoMTMxLCAxMzEsIDEzMSk7IGxpbmUtaGVpZ2h0OiAxLjVlbTsgZm9udC1zaXplOiAxOHB4OyIgY2xhc3M9IiI+Tm8gbW9yZSBmdW1ibGluZyB0byB1bmxvY2sgeW91ciBwaG9uZSBhbmQgZmluZCB5b3VyIG5vdGVzIGFwcDsgQ2hlYXRzaGVldCBpcyBhcyBlYXN5IGFzIHB1bGxpbmcgZG93biBjZW50ZXIsIHB1bGxpbmcgdXAgCnJvb21zLCBsaWNlbnNlIHBsYXRlcywgbHVnZ2FnZSBjb21iaW5hdGlvbiwgSUQgbnVtYmVycy4gYW55dGltZSBpbiB0aGUgVG9kYXkgV2lkZ2V0IG9yIHBhc3RlIHRoZW0gYW55d2hlcmUgd2l0aCB0aGUgQ3VzdG9tIEtleWJvYXJkLiZuYnNwOzwvc3Bhbj48L3NwYW4+ICAgICAgICAgICAgICAgIDwvZGl2PjxkaXY+PHNwYW4gc3R5bGU9ImxpbmUtaGVpZ2h0OiAxLjVlbTsgZm9udC1zaXplOiAxOHB4OyIgY2xhc3M9IiI+PHNwYW4gc3R5bGU9ImNvbG9yOiByZ2IoMTMxLCAxMzEsIDEzMSk7IGxpbmUtaGVpZ2h0OiAxLjVlbTsgZm9udC1zaXplOiAxOHB4OyIgY2xhc3M9IiI+PGJyPjwvc3Bhbj48L3NwYW4+PC9kaXY+CiAgICAgICAgICAgIA==[/md_live_text][md_button button_style="fill-oval" button_size="standard" left_right_padding="14" button_align="left" button_text="Read more" button_icon_class="icon-empty" button_color="rgb(25, 93, 255)" button_text_color="#fff" button_bg_hover_color="rgb(78, 129, 250)" button_hover_color="#FFF" button_url="#" button_target="_blank" ninja_popup_validate="no" ninja_popup_form_id="undefined" md_button_animation="yes" md_button_animation_type="fade" md_button_animation_speed="800" md_button_animation_delay="0.5" md_button_animation_position="right" md_button_animation_show="once" md_button_animation_easing="Power4.easeOut" md_button_parallax_speed="1" align="left"][/md_button][/vc_column]'
);
