<?php
$section_params = array(
    'row_type' => "image"
, 'type_width' => "full_size"
,'box_size_states' => "content_box_size"
,'el_class' => ''
,'row_fit_to_height' => "no"
,'row_vertical_align' => "no"
,'row_equal_column_heigh' => "no"
,'row_content_vertical_align' => "0"
,'background_color' => "rgba(255,255,255,1)"
,'row_webm_url' => ""
,'row_mp4_url' => ""
, 'background_color_image' => "rgba(0, 0, 0, 0)"
, 'row_image' => "http://theme.pixflow.net/massive-dynamic/section/section-11/Massive-Dynamic-1.jpg"
, 'row_padding_top' => "200"
, 'row_padding_bottom' => "200"
, 'row_padding_right' => "0"
, 'row_padding_left' => "0"
, 'row_margin_top' => "0"
, 'row_margin_bottom' => "0"
,'row_image_position' =>"default"
,'row_bg_image_size_tab_image' => "cover"
,'row_bg_repeat_image_gp' => "no"
,'first_color' => "#000"
,'second_color' => "#000"
,'row_gradient_color' => 'pixflow_base64eyJjb2xvcjEiOiIjZmZmIiwiY29sb3IyIjoicmdiYSgyNTUsMjU1LDI1NSwwKSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0='
,'row_image_position_gradient' => "fit"
,'row_bg_image_size_tab_gradient' => "cover"
,'row_bg_repeat_gradient_gp' => "no"
,'row_inner_shadow' => "no"
,'row_sloped_edge' => "no"
,'row_slope_edge_position' => "top"
,'row_sloped_edge_color' => "#000"
,'row_sloped_edge_angle' => "-3"
,'parallax_status' => "no"
,'parallax_speed' => "1"
, 'content' => '[vc_column el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgba(0,0,0,0)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="37"  padding_bottom="0" padding_left="0" border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);background-color:rgba(0,0,0,0);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:37px!important;padding-bottom:0px;padding-left:0px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}"  md_laptop_visibility="yes" md_tablet_portrait_visibility="yes" md_tablet_landscape_visibility="yes" md_mobile_portrait_visibility="yes" md_mobile_landscape_visibility="yes" md_tablet_portrait_width="12" padding-right="29"][md_live_text meditor_line_height="1"            meditor_letter_spacing="0"      align="left"]CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgPGgzIHN0eWxlPSJsaW5lLWhlaWdodDogMWVtOyI+PHNwYW4gc3R5bGU9ImZvbnQtZmFtaWx5OiBQb3BwaW5zOyBmb250LXdlaWdodDogNTAwOyBmb250LXN0eWxlOiBub3JtYWw7IGZvbnQtc2l6ZTogNDBweDsgbGluZS1oZWlnaHQ6IDFlbTsgY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsiIGNsYXNzPSIiIGRhdGEtZm9udC13ZWlnaHQ9IjUwMCI+U3RhcnR1cCBkcml2ZW48L3NwYW4+PC9oMz48aDMgc3R5bGU9ImxpbmUtaGVpZ2h0OiAxZW07Ij48c3BhbiBzdHlsZT0ibGluZS1oZWlnaHQ6IDFlbTsiIGNsYXNzPSIiPjxzcGFuIHN0eWxlPSJmb250LWZhbWlseTogUG9wcGluczsgZm9udC13ZWlnaHQ6IDUwMDsgZm9udC1zdHlsZTogbm9ybWFsOyBmb250LXNpemU6IDQwcHg7IGxpbmUtaGVpZ2h0OiAxZW07IGNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7IiBjbGFzcz0iIiBkYXRhLWZvbnQtd2VpZ2h0PSI1MDAiPmJ1c2luZXNzIGFuZCBhZ2VuY3k8L3NwYW4+PGJyPjwvc3Bhbj48L2gzPiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAg[/md_live_text][vc_empty_space height="19"][/vc_empty_space][md_separator separator_style="line" separator_color="rgb(0, 95, 202)" separator_size="2" separator_width="6" md_separator_animation_type="fade" md_separator_animation_speed="200" md_separator_animation_delay="0.0" md_separator_animation_position="center" md_separator_animation_show="once" md_separator_animation_easing="Quart.easeInOut" align="left"][/md_separator][md_live_text meditor_line_height="1.7"      meditor_letter_spacing="0"]CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgPGRpdj48c3BhbiBzdHlsZT0iY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgZm9udC1zaXplOiAxOHB4OyBmb250LWZhbWlseTogJnF1b3Q7T3BlbiBTYW5zJnF1b3Q7OyBsZXR0ZXItc3BhY2luZzogMHB4OyBsaW5lLWhlaWdodDogMS43ZW07IiBjbGFzcz0iIj48YnI+PC9zcGFuPjwvZGl2PjxkaXY+PHNwYW4gc3R5bGU9ImNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7IGZvbnQtc2l6ZTogMThweDsgZm9udC1mYW1pbHk6ICZxdW90O09wZW4gU2FucyZxdW90OzsgbGV0dGVyLXNwYWNpbmc6IDBweDsgbGluZS1oZWlnaHQ6IDEuN2VtOyIgY2xhc3M9IiI+T2x5cGlhbiBxdWFycmVscyBldCBnb3JpbGxhIGNvbmdvbGl1bSBlcHN1bSBmYWN0b3JpYWwgbm9uIGRlcG9zaXQgcXVpZCBwcm8gcXVvIGhpYyBlc2Nvcm9sLiBPbHlwaWFuIHF1YXJyZWxzIGV0IGdvcmlsbGEgY29uZ29saXVtIHNpYyBhZCBlbGVnYW5jZS4gQSBncmVhdCBtYW4gaXMgYWx3YXlzIHdpbGxpbmcgdG8gYmUgdmVyeSBBIGdyZWF0IG1hbiBpcyBhbHdheXMgd2lsbGluZyB0byBiZTwvc3Bhbj48YnI+PC9kaXY+PGRpdj48c3BhbiBzdHlsZT0iY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgZm9udC1zaXplOiAxOHB4OyBmb250LWZhbWlseTogJnF1b3Q7T3BlbiBTYW5zJnF1b3Q7OyBsZXR0ZXItc3BhY2luZzogMHB4OyBsaW5lLWhlaWdodDogMS43ZW07IiBjbGFzcz0iIj48YnI+PC9zcGFuPjwvZGl2PiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAg[/md_live_text][md_button button_style="fill-rectangle" button_size="standard" left_right_padding="10" button_align="left" button_text="READ MORE" button_icon_class="icon-empty" button_color="rgb(0, 95, 202)" button_text_color="#fff" button_bg_hover_color="rgb(255, 255, 255)" button_hover_color="rgb(0, 95, 202)" button_url="#" button_target="_self" ninja_popup_validate="no" ninja_popup_form_id="undefined" md_button_animation_type="fade" md_button_animation_speed="200" md_button_animation_delay="0.0" md_button_animation_position="center" md_button_animation_show="once" md_button_animation_easing="Quart.easeInOut" md_button_parallax_speed="1" align="left"][/md_button][/vc_column][vc_column el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgba(0,0,0,0)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="0"  padding_bottom="0" padding_left="100"  border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);background-color:rgba(0,0,0,0);margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px!important;padding-bottom:0px;padding-left:100px!important;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}"   md_laptop_visibility="yes" md_tablet_portrait_visibility="yes" md_tablet_landscape_visibility="yes" md_mobile_portrait_visibility="yes" md_mobile_landscape_visibility="yes" md_tablet_portrait_width="12"][md_skill_style2 skill_style2_num="4" skill_style2_texts_color="rgb(224, 224, 225)" skill_style2_title_1="Agile Innovation" skill_style2_percentage_1="80" skill_style2_color_1="rgb(64, 191, 102)" skill_style2_title_2="Macro Trends" skill_style2_percentage_2="90" skill_style2_color_2="rgb(64, 191, 102)" skill_style2_title_3="Agile Innovation" skill_style2_percentage_3="80" skill_style2_color_3="rgb(64, 191, 102)" skill_style2_title_4="Macro Trends" skill_style2_percentage_4="90" skill_style2_color_4="rgb(64, 191, 102)" skill_style2_title_5="Skill Title 5" skill_style2_percentage_5="40" skill_style2_color_5="#7b58c3" skill_style2_title_6="Skill Title 6" skill_style2_percentage_6="40" skill_style2_color_6="#7b58c3" skill_style2_title_7="Skill Title 7" skill_style2_percentage_7="40" skill_style2_color_7="#7b58c3" skill_style2_title_8="Skill Title 8" skill_style2_percentage_8="40" skill_style2_color_8="#7b58c3" skill_style2_title_9="Skill Title 9" skill_style2_percentage_9="40" skill_style2_color_9="#7b58c3" skill_style2_title_10="Skill Title 10" skill_style2_percentage_10="40" skill_style2_color_10="#7b58c3" md_skill_style2_animation_speed="200" md_skill_style2_animation_delay="0.0" md_skill_style2_animation_position="center" md_skill_style2_animation_show="once" md_skill_style2_animation_easing="Quart.easeInOut"][/md_skill_style2][/vc_column]'
);
