<?php
$section_params = array(
	'row_type' => "none"
,'type_width' =>'full_size'
,'row_fit_to_height'=>'enable'
,'box_size_states'=>'content_full_size'
,'el_class'=>''
,'row_vertical_align'=>'enable'
,'row_equal_column_heigh'=>'yes'
,'row_content_vertical_align'=>'middle'
,'row_padding_top'=>'0'
,'row_padding_bottom'=>'0'
,'row_padding_right'=>'0'
,'row_padding_left'=>'0'
,'row_margin_top'=>'0'
,'row_margin_bottom'=>'0'
,'background_color'=>'rgba(255,255,255,1)'
,'row_webm_url'=>''
,'row_mp4_url'=>''
,'background_color_image'=>'rgba(0, 0, 0, 0.2)'
,'row_image_position'=>'default'
,'row_bg_image_size_tab_image'=>'cover'
,'row_bg_repeat_image_gp='=>'no'
,'first_color'=>'#000'
,'second_color'=>'#000'
,'row_gradient_color'=>'pixflow_base64eyJjb2xvcjEiOiIjZmZmIiwiY29sb3IyIjoicmdiYSgyNTUsMjU1LDI1NSwwKSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0='
,'row_image_position_gradient'=>'fit'
,'row_bg_image_size_tab_gradient'=>'cover'
,'row_bg_repeat_gradient_gp'=>'no'
,'row_inner_shadow'=>'no'
,'row_sloped_edge'=>'no'
,'row_slope_edge_position'=>'top'
,'row_sloped_edge_color'=>'#000'
,'row_sloped_edge_angle'=>'-3'
,'parallax_status'=>'enable'
,'parallax_speed'=>'0'


, 'content' => '[vc_column el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgba(0,0,0,0)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="0" padding_bottom="0" padding_left="0" border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);border-style:solid;background-color:rgba(0,0,0,0);background-size:;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}" md_laptop_visibility="enable" md_tablet_portrait_visibility="enable" md_tablet_landscape_visibility="enable" md_tablet_portrait_width="12" md_mobile_portrait_visibility="enable" md_mobile_landscape_visibility="enable"][md_image_box_fancy image_box_fancy_image="http://theme.pixflow.net/massive-dynamic/section/section-48/23.jpg" image_box_fancy_height_type="manual" image_box_fancy_height="770" image_box_fancy_size="cover" image_box_fancy_icon="icon-empty" image_box_fancy_description_title="Fancy Image Box" image_box_fancy_description_text="Massive Dynamic has over 10 years of experience in Design. We take pride in delivering Intelligent Designs and Engaging Experiences for clients all over the World." image_box_fancy_style="normal" image_box_fancy_icon_color="rgb(255, 255, 255)" image_box_fancy_text_color="rgb(255, 255, 255)" image_box_fancy_background_color="rgba(127, 127, 127, 0.73)" image_box_fancy_effect_slider="fade" image_box_fancy_speed="3000" md_image_box_fancy_animation_type="fade" md_image_box_fancy_animation_speed="200" md_image_box_fancy_animation_delay="0" md_image_box_fancy_animation_position="center" md_image_box_fancy_animation_show="once" md_image_box_fancy_animation_easing="Quart.easeInOut" md_image_box_fancy_parallax_speed="1"][/md_image_box_fancy][/vc_column][vc_column el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgb(0, 91, 204)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="0" padding_bottom="0" padding_left="0" border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);border-style:solid;background-color:rgb(0, 91, 204);background-size:;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:0px;padding-bottom:0px;padding-left:0px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}" md_laptop_visibility="enable" md_tablet_portrait_visibility="enable" md_tablet_landscape_visibility="enable" md_tablet_portrait_width="12" md_mobile_portrait_visibility="enable" md_mobile_landscape_visibility="enable"][md_testimonial_carousel testimonial_carousel_num="1" testimonial_carousel_text_color="rgb(255, 255, 255)" testimonial_carousel_text_size="h6" testimonial_carousel_img_1="http://theme.pixflow.net/massive-dynamic/section/section-48/2.png" testimonial_carousel_name_1="Jessica Nobel" testimonial_carousel_job_name_1="Graphic Designer, Stupids Magazine" testimonial_carousel_desc_1="orem ipsum dolor sit amet, nec in adipiscing purus luctus, urna  fringilla vel, non sed arcu integevestibulum in lorem nec" testimonial_carousel_name_2="Mari Javani" testimonial_carousel_job_name_2="Graphic Designer, Stupids Magazine" testimonial_carousel_desc_2="orem ipsum dolor sit amet, nec in adipiscing purus luctus, urna pellentesque fringilla vel, non sed arcu integevestibulum in lorem nec" testimonial_carousel_name_3="Mari Javani" testimonial_carousel_job_name_3="Graphic Designer, Stupids Magazine" testimonial_carousel_desc_3="orem ipsum dolor sit amet, nec in adipiscing purus luctus, urna pellentesque fringilla vel, non sed arcu integevestibulum in lorem nec" testimonial_carousel_name_4="Mari Javani" testimonial_carousel_job_name_4="Graphic Designer, Stupids Magazine" testimonial_carousel_desc_4="orem ipsum dolor sit amet, nec in adipiscing purus luctus, urna pellentesque fringilla vel, non sed arcu integevestibulum in lorem nec" testimonial_carousel_name_5="Mari Javani" testimonial_carousel_job_name_5="Graphic Designer, Stupids Magazine" testimonial_carousel_desc_5="orem ipsum dolor sit amet, nec in adipiscing purus luctus, urna pellentesque fringilla vel, non sed arcu integevestibulum in lorem nec" md_testimonial_carousel_animation_type="fade" md_testimonial_carousel_animation_speed="200" md_testimonial_carousel_animation_delay="0" md_testimonial_carousel_animation_position="center" md_testimonial_carousel_animation_show="once" md_testimonial_carousel_animation_easing="Quart.easeInOut" md_testimonial_carousel_parallax_speed="1"][/md_testimonial_carousel][/vc_column]'
);
