<?php
$section_params = array(
	'row_type' => "none"
,'type_width' =>'full_size'
,'row_fit_to_height'=>'enable'
,'box_size_states'=>'content_box_size'
,'el_class'=>''
,'row_vertical_align'=>'enable'
,'row_equal_column_heigh'=>'enable'
,'row_content_vertical_align'=>'0'
,'row_padding_top'=>'190'
,'row_padding_bottom'=>'190'
,'row_padding_right'=>'0'
,'row_padding_left'=>'0'
,'row_margin_top'=>'0'
,'row_margin_bottom'=>'0'
,'background_color'=>'rgb(25, 25, 25)'
,'row_webm_url'=>''
,'row_mp4_url'=>''
,'background_color_image'=>'rgba(0, 0, 0, 0.2)'
,'row_image_position'=>'default'
,'row_bg_image_size_tab_image'=>'cover'
,'row_bg_repeat_image_gp='=>'no'
,'first_color'=>'#000'
,'second_color'=>'#000'
,'row_gradient_color'=>'pixflow_base64eyJjb2xvcjEiOiIjZmZmIiwiY29sb3IyIjoicmdiYSgyNTUsMjU1LDI1NSwwKSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0='
,'row_image_position_gradient'=>'fit'
,'row_bg_image_size_tab_gradient'=>'cover'
,'row_bg_repeat_gradient_gp'=>'no'
,'row_inner_shadow'=>'no'
,'row_sloped_edge'=>'no'
,'row_slope_edge_position'=>'top'
,'row_sloped_edge_color'=>'#000'
,'row_sloped_edge_angle'=>'-3'
,'parallax_status'=>'enable'
,'parallax_speed'=>'0'


, 'content' => '[vc_column el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgba(0,0,0,0)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="167" padding_bottom="0" padding_left="100" border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);border-style:solid;background-color:rgba(0,0,0,0);background-size:;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:167px;padding-bottom:0px;padding-left:100px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}" md_laptop_visibility="enable" md_tablet_portrait_visibility="enable" md_tablet_landscape_visibility="enable" md_tablet_portrait_width="12" md_mobile_portrait_visibility="enable" md_mobile_landscape_visibility="enable"][vc_empty_space height="42"][/vc_empty_space][md_iconbox_side2 iconbox_side2_icon="icon-ribbon" iconbox_side2_title="" iconbox_side2_small_title_color="false" iconbox_side2_title_big="Device Friendly" iconbox_side2_description="It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. " iconbox_side2_title_big_heading="h6" iconbox_side2_type="image" iconbox_side2_image="http://theme.pixflow.net/massive-dynamic/section/section-43/1aa.png" iconbox_side2_alignment="left" iconbox_side2_general_color="rgb(255, 255, 255)" iconbox_side2_icon_color="rgba(0,0,0,.5)" iconbox_side2_button="no" iconbox_side2_button_style="fade-square" iconbox_side2_button_text="Read more" iconbox_side2_class="icon-empty" iconbox_side2_button_color="#5e5e5e" iconbox_side2_button_text_color="#fff" iconbox_side2_button_bg_hover_color="#9b9b9b" iconbox_side2_button_hover_color="#FFF" iconbox_side2_button_size="standard" iconbox_side2_left_right_padding="0" iconbox_side2_button_url="#" iconbox_side2_button_target="_self" md_iconbox_side2_animation="yes" md_iconbox_side2_animation_type="fade" md_iconbox_side2_animation_speed="800" md_iconbox_side2_animation_delay="0.3" md_iconbox_side2_animation_position="left" md_iconbox_side2_animation_show="once" md_iconbox_side2_animation_easing="Power4.easeOut" md_iconbox_side2_parallax_speed="1"][/md_iconbox_side2][md_iconbox_side2 iconbox_side2_icon="icon-ribbon" iconbox_side2_title="" iconbox_side2_small_title_color="false" iconbox_side2_title_big="Money & Time Saving" iconbox_side2_description="It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. " iconbox_side2_title_big_heading="h6" iconbox_side2_type="image" iconbox_side2_image="http://theme.pixflow.net/massive-dynamic/section/section-43/2aa.png" iconbox_side2_alignment="left" iconbox_side2_general_color="rgb(255, 255, 255)" iconbox_side2_icon_color="rgba(0,0,0,.5)" iconbox_side2_button="no" iconbox_side2_button_style="fade-square" iconbox_side2_button_text="Read more" iconbox_side2_class="icon-empty" iconbox_side2_button_color="#5e5e5e" iconbox_side2_button_text_color="#fff" iconbox_side2_button_bg_hover_color="#9b9b9b" iconbox_side2_button_hover_color="#FFF" iconbox_side2_button_size="standard" iconbox_side2_left_right_padding="0" iconbox_side2_button_url="#" iconbox_side2_button_target="_self" md_iconbox_side2_animation="yes" md_iconbox_side2_animation_type="fade" md_iconbox_side2_animation_speed="800" md_iconbox_side2_animation_delay="0.3" md_iconbox_side2_animation_position="left" md_iconbox_side2_animation_show="once" md_iconbox_side2_animation_easing="Power4.easeOut" md_iconbox_side2_parallax_speed="1"][/md_iconbox_side2][/vc_column][vc_column el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgba(0,0,0,0)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="100" padding_bottom="0" padding_left="0" border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);border-style:solid;background-color:rgba(0,0,0,0);background-size:;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:100px;padding-bottom:0px;padding-left:0px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}" md_laptop_visibility="enable" md_tablet_portrait_visibility="enable" md_tablet_landscape_visibility="enable" md_tablet_portrait_width="12" md_mobile_portrait_visibility="enable" md_mobile_landscape_visibility="enable"][md_image_box_slider image_box_slider_image="http://theme.pixflow.net/massive-dynamic/section/section-43/15.jpg" image_box_slider_height="420" image_box_slider_size="cover" image_box_slider_hover_link="" image_box_slider_hover_link_target="_self" image_box_slider_effect_slider="fade" image_box_slider_speed="3000" image_box_slider_hover="no" image_box_slider_hover_effect="text" image_box_slider_hover_text="Text Hover" image_box_slider_hover_text_effect="light" md_image_box_slider_animation="yes" md_image_box_slider_animation_type="fade" md_image_box_slider_animation_speed="800" md_image_box_slider_animation_delay="0.3" md_image_box_slider_animation_position="center" md_image_box_slider_animation_show="once" md_image_box_slider_animation_easing="Power4.easeOut" md_image_box_slider_parallax_speed="1"][/md_image_box_slider][/vc_column]'
);
