<?php
$section_params = array(
	'row_type' => "image"
,'type_width' =>'full_size'
,'row_fit_to_height'=>'enable'
,'box_size_states'=>'content_box_size'
,'el_class'=>''
,'row_vertical_align'=>'enable'
,'row_equal_column_heigh'=>'enable'
,'row_content_vertical_align'=>'0'
,'row_padding_top'=>'300'
,'row_padding_bottom'=>'300'
,'row_padding_right'=>'0'
,'row_padding_left'=>'0'
,'row_margin_top'=>'0'
,'row_margin_bottom'=>'0'
,'background_color'=>'rgba(255,255,255,1)'
,'row_webm_url'=>''
,'row_mp4_url'=>''
,'background_color_image'=>'rgba(0, 0, 0, 0)'
,'row_image_position'=>'default'
,'row_bg_image_size_tab_image'=>'cover'
,'row_bg_repeat_image_gp='=>'no'
,'first_color'=>'#000'
,'second_color'=>'#000'
,'row_gradient_color'=>'pixflow_base64eyJjb2xvcjEiOiIjZmZmIiwiY29sb3IyIjoicmdiYSgyNTUsMjU1LDI1NSwwKSIsImNvbG9yMVBvcyI6IjAuMDAiLCJjb2xvcjJQb3MiOiIxMDAuMDAiLCJhbmdsZSI6MH0='
,'row_image_position_gradient'=>'fit'
,'row_bg_image_size_tab_gradient'=>'cover'
,'row_bg_repeat_gradient_gp'=>'no'
,'row_inner_shadow'=>'no'
,'row_sloped_edge'=>'no'
,'row_slope_edge_position'=>'top'
,'row_sloped_edge_color'=>'#000'
,'row_sloped_edge_angle'=>'-3'
,'parallax_status'=>'yes'
,'parallax_speed'=>'1'
,'row_image' => 'http://theme.pixflow.net/massive-dynamic/section/section-39/10.jpg'

, 'content' => '[vc_column width="6/12"][/vc_column][vc_column el_class="" width="6/12" border_color="rgba(0,0,0,1)" border_style="solid" background_color="rgba(0,0,0,0)" margin_top="0" margin_right="0" margin_bottom="0" margin_left="0" padding_top="0" padding_right="65" padding_bottom="0" padding_left="153" border_top_width="0" border_right_width="0" border_bottom_width="0" border_left_width="0" css="{border-color:rgba(0,0,0,1);border-style:solid;background-color:rgba(0,0,0,0);background-size:;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;padding-top:0px;padding-right:65px;padding-bottom:0px;padding-left:153px;border-top-width:0px;border-right-width:0px;border-bottom-width:0px;border-left-width:0px;}" md_laptop_visibility="enable" md_tablet_portrait_visibility="enable" md_tablet_landscape_visibility="enable" md_tablet_portrait_width="12" md_mobile_portrait_visibility="enable" md_mobile_landscape_visibility="enable"][md_live_text meditor_letter_spacing="0"    meditor_line_height="1"    md_live_text_animation="yes" md_live_text_animation_type="fade" md_live_text_animation_speed="800" md_live_text_animation_delay="0.3" md_live_text_animation_position="right" md_live_text_animation_show="once" md_live_text_animation_easing="Power4.easeOut" md_live_text_parallax_speed="1"  align="left"]CiAgICAgICAgICAgICAgICA8ZGl2PgogICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9ImxpbmUtaGVpZ2h0OiAxLjJlbTsiIGNsYXNzPSJrZWVwLXRleHQtc2VsZWN0ZWQiPjxzcGFuIHN0eWxlPSJsaW5lLWhlaWdodDogMS4yZW07IiBjbGFzcz0iIj48c3BhbiBzdHlsZT0iZm9udC1zaXplOiA0MHB4OyBjb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyBsaW5lLWhlaWdodDogMS4yZW07Ij5XYXRjaCB0aGUgdmlkZW87Jm5ic3A7PC9zcGFuPjwvc3Bhbj48L3NwYW4+PGRpdj48c3BhbiBzdHlsZT0ibGluZS1oZWlnaHQ6IDEuMmVtOyIgY2xhc3M9ImtlZXAtdGV4dC1zZWxlY3RlZCI+PHNwYW4gc3R5bGU9ImxpbmUtaGVpZ2h0OiAxLjJlbTsiIGNsYXNzPSIiPjxzcGFuIHN0eWxlPSJmb250LXNpemU6IDQwcHg7IGNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7IGxpbmUtaGVpZ2h0OiAxLjJlbTsiIGNsYXNzPSIiPkl04oCZcyBlYXN5IHRvIHdvcmsgd2l0aDwvc3Bhbj48L3NwYW4+PC9zcGFuPjwvZGl2PiAgICAgICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgICAg[/md_live_text][md_live_text meditor_letter_spacing="0"    meditor_line_height="1"    md_live_text_animation="yes" md_live_text_animation_type="fade" md_live_text_animation_speed="800" md_live_text_animation_delay="0.4" md_live_text_animation_position="right" md_live_text_animation_show="once" md_live_text_animation_easing="Power4.easeOut" md_live_text_parallax_speed="1"]CiAgICAgICAgICAgICAgICA8ZGl2PjxzcGFuIHN0eWxlPSJsaW5lLWhlaWdodDogMS41ZW07IGZvbnQtc2l6ZTogMThweDsiIGNsYXNzPSIiPjxzcGFuIHN0eWxlPSJsaW5lLWhlaWdodDogMS41ZW07IGZvbnQtc2l6ZTogMThweDsiIGNsYXNzPSIiPjxzcGFuIHN0eWxlPSJjb2xvcjogcmdiKDIyNCwgMjI0LCAyMjQpOyBsaW5lLWhlaWdodDogMS41ZW07IGZvbnQtc2l6ZTogMThweDsiIGNsYXNzPSIiPjxicj48L3NwYW4+PC9zcGFuPjwvc3Bhbj48L2Rpdj48ZGl2PgogICAgICAgICAgICAgICAgICAgPHNwYW4gc3R5bGU9ImxpbmUtaGVpZ2h0OiAxLjVlbTsgZm9udC1zaXplOiAxOHB4OyIgY2xhc3M9IiI+PHNwYW4gc3R5bGU9ImxpbmUtaGVpZ2h0OiAxLjVlbTsgZm9udC1zaXplOiAxOHB4OyIgY2xhc3M9IiI+PHNwYW4gc3R5bGU9ImNvbG9yOiByZ2IoMjI0LCAyMjQsIDIyNCk7IGxpbmUtaGVpZ2h0OiAxLjVlbTsgZm9udC1zaXplOiAxOHB4OyIgY2xhc3M9IiI+Tm8gbW9yZSBmdW1ibGluZyB0byB1bmxvY2sgeW91ciBwaG9uZSBhbmQgZmluZCB5b3VyIG5vdGVzIGFwcDsgQ2hlYXQgc2hlZXQgaXMgYXMgZWFzeSBhcyBwdWxsaW5nIGRvd24gY2VudGVyLCBwdWxsaW5nIHVwIHRoZSBrZXlib2FyZCwgb3IgZ2xhbmNpbmcgYXQgeW91ciBBcHBsZSBDaGVhdCBzaGVldCBhbmQgdGhlbiByZWZlciB0byB0aGVtIGFueXRpbWUgaW4gdGhlIFRvZGF5IFdpZGdldCBvciBwYXN0ZSB0aGVtIGFueXdoZXJlIHdpdGggdGhlIEN1c3RvbSBLZXlib2FyZC4mbmJzcDs8L3NwYW4+PC9zcGFuPjwvc3Bhbj4gICAgICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICAgIA==[/md_live_text][/vc_column]'
);
