<?php die(); ?><?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="//localhost:8888/adithi_chandrashekar/wp-content/plugins/wordpress-seo/css/main-sitemap.xsl"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<sitemap>
		<loc>http://localhost:8888/adithi_chandrashekar/post-sitemap.xml</loc>
		<lastmod>2015-11-22T05:40:06-06:00</lastmod>
	</sitemap>
	<sitemap>
		<loc>http://localhost:8888/adithi_chandrashekar/page-sitemap.xml</loc>
		<lastmod>2018-05-24T07:17:36-05:00</lastmod>
	</sitemap>
	<sitemap>
		<loc>http://localhost:8888/adithi_chandrashekar/portfolio-sitemap.xml</loc>
		<lastmod>2018-05-24T05:20:06-05:00</lastmod>
	</sitemap>
	<sitemap>
		<loc>http://localhost:8888/adithi_chandrashekar/category-sitemap.xml</loc>
		<lastmod>2015-11-22T05:40:06-06:00</lastmod>
	</sitemap>
	<sitemap>
		<loc>http://localhost:8888/adithi_chandrashekar/post_tag-sitemap.xml</loc>
		<lastmod>2015-11-22T05:40:06-06:00</lastmod>
	</sitemap>
	<sitemap>
		<loc>http://localhost:8888/adithi_chandrashekar/skills-sitemap.xml</loc>
		<lastmod>2018-05-24T05:20:06-05:00</lastmod>
	</sitemap>
</sitemapindex>
<!-- XML Sitemap generated by Yoast SEO -->